import twitter
from collections import deque
api = twitter.Api(consumer_key='6GhjLPbZahCKk4gpLtFCa0XSh',
                      consumer_secret='Q1rPti2CMnEH555ZSUjTymg5KP1RAzi0PpKjjp0tXYNS27IP2K',
                      access_token_key='1259788333-dmMU7hlLFvT8z1dQDKKbjUHn3x4EQMo5QkY4tEY',
                      access_token_secret='uV4qboOa6QWcZbiojRIMaSrAJ5bowVOEnUiqpO2zeZWAJ',
                      cache=None)

screen_names1 = ['naravosubum', 'pokesimecic', 'vigeguvyjan', 'mywigerowapo', 'xurytebujeme', 'sedafagazen', 'xicurojymem', 'famidikupima', 'sazexobabibi', 'nylabemulez', 'limitesuzyn', 'xiqityrykux', 'cyzetebugajo', 'pupepehesiwi', 'suxopyqepuh', 'gedelimipohu', 'dynatomypyqu', 'fijawunajoza', 'puzukepubaz', 'wugosawabol', 'jimosypuxix', 'mivulobigizy', 'kihytuzuhyw', 'cylusemoryvu', 'penejeqisuj', 'rocajebazax', 'xebohuzynyfa', 'ququparimyp', 'cilynuviduz', 'hifutuvuzyl', 'gehixolavaj', 'syjugigyfew', 'hezazyvysywa', 'woxyhadyjon', 'tymotosoxedi', 'vixidimoxaf', 'vekumikowiky', 'gytabecuderi', 'zevocybikeju', 'xusonoquset', 'jypivesirasu', 'relopubopose', 'hycawofyhuru', 'xiguqecinazo', 'lanirajepube', 'pyhoposuled', 'sytylepoxof', 'jecimiticavi', 'qibyryqimesy', 'qazityvenybi', 'jufuluwaryvy', 'bedelovuciwi', 'noworoxyxav', 'qoqelabosub', 'fymehafecek', 'qalytyjawin', 'moledonywyz', 'zewibydupuxi', 'fynarejogyf', 'mywomomifej', 'vuriwexidobi', 'hyhexylopoq', 'zahubybedapo', 'norenopodyp', 'xuqacutyhul', 'muketaxuzyr', 'fewiwodygyga', 'lucytodyhys', 'mebadakovopy', 'benamawybig', 'jerejybavuwu', 'cewohuceqor', 'hunejelecyho', 'patugosatob', 'safalagocaz', 'relylizodaf', 'fiqocabotyv', 'jiqitecewawy', 'tobulalihena', 'fewezemuqywu', 'demoqilywuha', 'mesinepesur', 'jagakiwyvumu', 'zynacisetymo', 'lyjocufecup', 'zyrytyjawobo', 'fohihefidaw', 'wasetowadyha', 'mujysinunobu', 'hetepibozur', 'domevalodal', 'sifogiqedyxa', 'nugeqysikupy', 'fadyjojyxebu', 'mupehejecah', 'wyjomoqodul', 'qatujyqejyvo', 'sipyfujagyfu', 'wumaxigasom']
screen_names2 = ['nenacebagovu','nynybadopiso','vejokywaker','godefezocylo','kacifenexuf','vukyporylil','haxidoqydoh','xyjacejuvydo','mucomacixedu','zoqanimibis','taruzoqilud','mapapilufok','nepusegosota','nimykevukuxe','tyzimeqotedo','durubacuxiv','najyrexilox','minylocexov','padanirivuw','sutypotaxik','qajapetycyqo','xemamagurah','pobamirilexi','vaquzybikate','ritawurytax','qikividohyh','fukutavibobe','parozyretyt','gobutuditudi','jupufysyhym','mybedyjopiq','gupinepocid','lacufitidufu','kuhityxuhoq','kuvyxokunaze','wykywogofuf','sijiqopyfas','fexilyseryzi','dififiqobopu','kipobohuvyt','daqikyxacama','riziqytakega','zawaqufolyhu','cegezepuvex','qodexyrikequ','cowuferyhyb','wifazyryzyr','sofodotynuty','lupyfapapib','rowenapowuci','qakaqosihiq','cisuqavopib','lunomycemuz','jowowyxolujy','wykigybelynu','siguxemimak','rahymyvafiha','xidebywavopy','kidemekibary','hacyzamupuma','jamucagyjib','jeholetifyl','wocosujupub','lyrobadituw','gujuqativig','tekyriryvuxy','myvatidipexe','pedolomafun','tafenufugobu','qigifylytex','wupalovycuwi','mykifosyvero','ryhofohagijy','nibuwibyloc','hebobutonix','rowoqehipacu','qyjycucadan','kejobyfevij','cimuzijyfego','syviwihuqobu','rexigagofuqe','fefeqedyhuza','tyfylunyhoq','buwyxuqanedo','xezyhupolely','desihafevib','wusotazyjok','sizeryfajyr','dekirugolov','kucikymeqag','zivuqotycyq','wygojolikini','redebomizop','luzimohyquze','vamulovukuw','xagavaqecyh','kivazijezuwu','bafonexobog','fisifovyvev','rapyjugurozy']
screen_names3 = ['nihaporobys','wyjaborygoga','sivycypycas','mykufuqaqur','faqyhucodys','pivabetipeka','huqasamisedi','fafoqytahahe','zivuvatysam','zarynysowaqy','gyhegyfemica','nekohevajeh','janyrokidyzu','xytudaxaxyx','lorykugidys','guvuvasuzabo','hijixanupalo','fezabotyhat','mujytapycede','hiduzisecyr','rofihaduvipu','gezyboxyviji','jojawivysydu','jynykixukiq','mykeqyhuselu','rysigytozygi','hehiciwicyp','gaqinegiquli','zemotysydunu','barulufujupe','juxuhawydep','sofamazadyvo','satobitebyp','juhizimexiv','vemihifapoh','peqiliquqice','texemigenyna','vitibyxywik','myciwuzuzid','tydesucatifa','vamycuvajyvu','tomozucucope','tybudenajyf','qizafagagid','xisuxacubof','tulyliqycir','zedysyjygubu','konelyjapev','xynehuvutil','gawygynatofi','vygocaraqym']
users = api.UsersLookup(screen_name=screen_names3)

print [u.__dict__ for u in users]